# Generated by Django 5.2.12 on 2026-04-09 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange', models.CharField(choices=[('KRAKEN', 'Kraken')], default='KRAKEN', max_length=20)),
                ('api_key_encrypted', models.TextField()),
                ('api_secret_encrypted', models.TextField()),
                ('connected', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exchange_connections',
            },
        ),
    ]
