# Generated by Django 5.2.12 on 2026-04-09 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('trading_state', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=10)),
                ('state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_accounts',
            },
        ),
    ]
