# Generated by Django 5.2.12 on 2026-04-10 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.TextField(default='BTC/USD')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('size_btc', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.TextField(default='BTC/USD')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('executed_at', models.DateTimeField()),
                ('kraken_order_id', models.TextField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-executed_at'],
            },
        ),
    ]
