# Generated by Django 5.2.12 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(default='BTC/USD')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'candles',
                'ordering': ['-time'],
                'unique_together': {('time', 'symbol')},
            },
        ),
    ]
